import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './components/NavBar'
import Swapwidget from './components/Swapwidget'
import Footer from './components/Footer'
import { ClerkProvider } from '@clerk/nextjs'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TokenDisc',
  description: 'Generated by TokenDisc',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <NavBar />
          <main className=''>
            {children}
          </main>
          <Swapwidget />
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  )
}
